### ISSUE TITLE
Could not find com.github.vestrel00:contacts-android:0.1.8. After adding the dependencies then sync. Library is not found.

### ISSUE THREAD

**Issue by visherandro** [vestrel00/contacts-android#111] opened 2021-11-28 17:34 UTC
What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.vestrel00:contacts-android:0.1.8.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/vestrel00/contacts-android/0.1.8/contacts-android-0.1.8.pom
       - https://repo.maven.apache.org/maven2/com/github/vestrel00/contacts-android/0.1.8/contacts-android-0.1.8.pom
       - https://jcenter.bintray.com/com/github/vestrel00/contacts-android/0.1.8/contacts-android-0.1.8.pom

**Comment by vestrel00** [comment] 2021-11-28 17:39
Whoah! Hmm... I didn't think I touched anything related to JitPack publishing with the 0.1.8 release. Everything was working fine in 0.1.7. 

I'll start a new project and I'll try to add this lib as a dependency and see if I can reproduce. Thanks for bringing this up! 

🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥

**Comment by vestrel00** [comment] 2021-11-28 18:10
I'm unable to reproduce the issue. I created a new project using Android Studio 4.1 and followed the steps in the README. The new project is able to fetch this library just fine and the project builds and compiles.

Just making sure, @visherandro, you did do the following correct?

Add the include JitPack in the repositories list. So, for example, in your root `build.gradle`,

```groovy
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```

There are other ways to do this, which is why I did not include `allprojects` in the README.

Then in your library/app module's `build.gradle`

```groovy
dependencies {
     implementation 'com.github.vestrel00:contacts-android:0.1.8'
}
```

If you did all of that, I suggest invalidating your caches and restart. It typically fixes dependency issues for me in large projects.

<img width="472" alt="Screen Shot 2021-11-28 at 8 08 37 AM" src="https://user-images.githubusercontent.com/4332753/143780402-19a01e84-12e2-462f-9cbd-70f5f1e1f0c6.png">

Let me know how it goes 😄

**Comment by vestrel00** [comment] 2021-11-28 20:52
🤦, I did not mean to reference this issue with my commit in https://github.com/vestrel00/contacts-android/commit/f5dcb0e131b991356bcfafd2c7322ad5cb5acbac . Ignore it.

**Comment by vestrel00** [comment] 2021-12-05 21:36
Closing this. Please re-open if you are still having trouble adding the dependency 😁

**Closed by vestrel00** 2021-12-05 21:36 UTC
Labels: build

**Comment by shyambandla** [comment] 2021-12-30 13:43
maven { url "https://jitpack.io" }


add this to settings.gradle
