### ISSUE TITLE
Limit and Offset not working correctly 

### ISSUE THREAD

**Issue by PiotrPrus** [vestrel00/contacts-android#350] opened 2024-06-03 11:06 UTC
New user of library here 👋. Thank you so much for it. I need to add contacts screen to the app, nothing fancy. When I fetch contacts using this query:
```            
contactsApi
                .queryWithPermission()
                .include { Name.all + Phone.all + Contact.PhotoThumbnailUri }
                .where { (Name.DisplayName startsWith searchText) }
                .orderBy(ContactsFields.DisplayNamePrimary.asc())
                .findWithContext()
```
I got 300+ contacts and everything works smoothly. When I am adding paging limit and offset it starts to act weird. It scrolls to 150 offset and stops. the last list has 9 elements, where my loadSize is 10, so the paging stops. I tried and hardcoded offset 150, limit 10 and it gives 9 elements which is not true. 
Here is the query with limit and offset:
```            
contactsApi
                .queryWithPermission()
                .include { Name.all + Phone.all + Contact.PhotoThumbnailUri }
                .where { (Name.DisplayName startsWith searchText) }
                .orderBy(ContactsFields.DisplayNamePrimary.asc())
                .limit(limit)
                .offset(offset)
                .findWithContext()
```
The problem is clearly that list.size is smaller then limit. Even if I test other offsets like 160, 200, 300 it gives the results but some reason some of them are not a full list. Maybe some contacts are malfunctioning and that breaks the query?

**Comment by vestrel00** [comment] 2024-06-03 16:55
Hey @PiotrPrus, thanks for taking interest in this lib! I copy-pasted your query code into the sample app in the repo and am not able to reproduce the issue.

 I used a very simple scenario. I created 300 contacts. Each contact has no data beside the name. Each contact is named "Contact 1xxx" where "xxx" is a number from 1 to 300. Here's the code I used to generate the test contacts;

```kotlin
for (i in 1..300) {
  contactsApi
      .insertWithPermission()
      .rawContact {
          setName {
              displayName = "Contact ${1000 + i}"
          }
      }
      .commitAsync()
```

I then modified `ContactsActivity.kt` to show only 10 contacts per page (`limit(10)`) starting at offset 0 and loading the next page every time the refresh button in the toolbar is clicked. Take a look at the recording below.

https://github.com/vestrel00/contacts-android/assets/4332753/df38b1cd-104a-4b30-8f06-415a10e39ae5

_Note that I had to also include `Contact.DisplayNamePrimary` because that is what the sample app uses to display in the list. Other than that, the query is a direct copy-paste._

---------

>  Maybe some contacts are malfunctioning and that breaks the query?

Perhaps. I would really like to see the set of contacts that is able to reproduce this issue. Could you please help me with that?

It would make things easier to be able to reproduce the issue using a smaller number of contacts (300+ is a lot when trying to debug an issue). I would suggest creating around 10 to 20 test contacts with some test data where the issue is reproducible. Use smaller `limit` like 2, 3, 4, or 5.

Looking forward to your reply! I'm not marking this as a bug yet until I am able to reproduce it on my end because it's not impossible that the bug is not with the library =)

**Comment by vestrel00** [comment] 2024-08-13 16:46
Closing this for now because no feedback.

**Closed** 2024-08-13 16:47 UTC
