### ISSUE TITLE
Oppo A9 (2020) - LIMIT and OFFSET APIs are not working 

### ISSUE THREAD

**Issue by itinsidenews** [vestrel00/contacts-android#252] opened 2022-08-05 23:31 UTC
I am using this library for a long time Now I needed to add a pagination feature. but problem is that limit and offset are not working. this library  ignoring value of limit and offset.

**Comment by vestrel00** [comment] 2022-08-05 23:35
What version of this library are you using? Can you please try the latest version; 0.2.3.

This sounds like a duplicate of #217, which I already fixed. Or, it could be related to these two issues; #241 and #243, both of which are already resolved.

Thanks for being a user of this lib btw 🙏

**Comment by itinsidenews** [comment] 2022-08-06 00:14
First of all, thank you for your quick reply. I am using the current latest version of this library  **0.2.3**. and the testing phone is oppo  A9 2020, Android OS 11.  It looks like my device doesn't support contacts pagination as you mentioned in issue no #243. I will try to implement the solution that you have mentioned in issue no #243  and will let you know. I think this function would be very helpful **forceOffsetAndLimit(Boolean)**

**Comment by vestrel00** [comment] 2022-08-06 00:37
> the testing phone is oppo A9 2020, Android OS 11

I see. I added this to the list of devices that does not support limit and offset functions; https://github.com/vestrel00/contacts-android/discussions/242#discussioncomment-3337613

> This forceOffsetAndLimit(Boolean) function would be very helpful if you will add it in the next version.

I created an issue for this;  #253 

I will include it as part of the next release; **[0.2.4](https://github.com/vestrel00/contacts-android/discussions/248)**

> Thanks

My pleasure! And, thank you for raising an issue 🍻

**Closed** 2022-08-06 00:40 UTC
