### ISSUE TITLE
Deleting contacts in Xiaomi phones fails

### ISSUE THREAD

**Issue by asker517** [vestrel00/contacts-android#293] opened 2023-08-07 13:17 UTC
I just use 
```kotlin
      val ids = contacts.map { it.id }
        val data = Contacts(context).rawContactsQuery().where { Contact.Id `in` ids }.find()
```
data result is right,contact is exist,and then do delete
```kotlin
val result = Contacts(context).delete().rawContactsWithId(ids).contactsWithId(ids).commit()
```
result log:
```txt
Delete.Result {
    isSuccessful: false
    rawContactIdsResultMap: {197=false}
    contactIdsResultMap: {197=false}
    whereResultMap: {}
     isRedacted: false
 }
```
result is failed...it seems not find the delete id?...is there something wrong with my code ?  :-(

**Comment by vestrel00** [comment] 2023-08-07 17:44
Hey @asker517, I copy-pasted your code and I am not able to reproduce the issue. The Contacts and RawContacts are successfully getting deleted for me.

There may be several reasons why the delete is failing for you.
1. The permission `android.permission.WRITE_CONTACTS` has not yet been granted. 
2. The Contacts/RawContacts that are failing deletion are read-only. Please read this discussion as this has been discussed before; https://github.com/vestrel00/contacts-android/discussions/224#discussioncomment-2950542

**Please try deleting the same Contact/RawContact using the default Contacts app of the device. See if it will work.**

**Comment by vestrel00** [comment] 2023-08-07 17:45
Also, this line of code you gave;

```kotlin
val result = Contacts(context).delete().rawContactsWithId(ids).contactsWithId(ids).commit()
```

Can be shortened to;

```kotlin
val result = Contacts(context).delete().contactsWithId(ids).commit()
```

...assuming that `ids` are the IDs of Contacts (not RawContacts). Please keep in mind that Contacts and RawContacts are different. Sometimes their IDs match but sometimes they don't.

**Comment by asker517** [comment] 2023-08-08 03:26
@vestrel00 thank you very much, i will have a try, i'm sure permission has been granted

**Comment by asker517** [comment] 2023-08-08 03:53
> Hey @asker517, I copy-pasted your code and I am not able to reproduce the issue. The Contacts and RawContacts are successfully getting deleted for me.
> 
> There may be several reasons why the delete is failing for you.
> 
> 1. The permission `android.permission.WRITE_CONTACTS` has not yet been granted.
> 2. The Contacts/RawContacts that are failing deletion are read-only. Please read this discussion as this has been discussed before; [Why are these RawContact deletions failing? #224 (comment)](https://github.com/vestrel00/contacts-android/discussions/224#discussioncomment-2951518)
> 
> **Please try deleting the same Contact/RawContact using the default Contacts app of the device. See if it will work.**

..may because i just test on "Xiaomi" device ...I changed emulator ,worked nice...
so , is there any way(API) to delete on xiaomi devices..

**Comment by vestrel00** [comment] 2023-08-08 04:25
> ..may because i just test on "Xiaomi" device ...I changed emulator ,worked nice...
> 
> so , is there any way(API) to delete on xiaomi devices..

So, I'm actually not sure if deletion fails on Xiaomi **devices** or Xiaomi **accounts**. I think the issue is with Xiaomi accounts. The issue might be reproducible on the emulator if you can add a Xioami account and contacts belonging to that account.

Can you install a contacts app on that Xiaomi device, for example the [Google Contacts app](https://play.google.com/store/apps/details?id=com.google.android.contacts)? Then, try deleting the same contacts that this library fails to delete using that Contacts app. If the delete fails, then I don't think there is anything we can do. If you are able to delete those Xiaomi Contacts using any Contacts app, please let me know.

**Comment by asker517** [comment] 2023-08-08 05:45
> > ..may because i just test on "Xiaomi" device ...I changed emulator ,worked nice...
> > so , is there any way(API) to delete on xiaomi devices..
> 
> So, I'm actually not sure if deletion fails on Xiaomi **devices** or Xiaomi **accounts**. I think the issue is with Xiaomi accounts. The issue might be reproducible on the emulator if you can add a Xioami account and try deleting contacts belonging to that Xiaomi account.
> 
> Can you install a contacts app on that Xiaomi device, for example the [Google Contacts app](https://play.google.com/store/apps/details?id=com.google.android.contacts)? Then, try deleting the same contacts that this library fails to delete using that Contacts app. If the delete fails, then I don't think there is anything we can do. If you are able to delete those Xiaomi Contacts using any Contacts app, please let me know.

yes,i have tried Google Contact app，then choose Xiaomi account in app,it will show all Contacts, and the do delete contact,it worked fine..local contact will be deleted!

**Comment by vestrel00** [comment] 2023-08-08 06:05
> yes,i have tried Google Contact app，then choose Xiaomi account in app,it will show all Contacts, and the do delete contact,it worked fine..local contact will be deleted!

You did this in an emulator or a Xiaomi phone?

**Comment by asker517** [comment] 2023-08-08 07:07
> > yes,i have tried Google Contact app，then choose Xiaomi account in app,it will show all Contacts, and the do delete contact,it worked fine..local contact will be deleted!
> 
> You did this in an emulator or a Xiaomi phone?
> 
> On the same emulator/phone where the delete succeeded, does the following code succeed in deleting a similar contact from a Xiaomi account? Or does it fail?
> 
> ```kotlin
> Contacts(context).delete().contactsWithId(ids).commit()
> ```
> 
> Also, could you tell me exactly what Xiaomi/Redmi phone you are using? I'm looking to buy a cheap one so I can debug the issue, if necessary.

I just test the code 
```kotlin
Contacts(context).delete().contactsWithId(ids).commit()
```
on emulator,it worked correctly, but not work on my xiaomi phone
I test same code  on Xiaomi phone, / Xiaomi 13 / MIUI 14.0.30 based on Android 13..not worked.  but when i used google contact app,it will do delete well.

**Comment by vestrel00** [comment] 2023-08-08 07:45
> I test same code  on Xiaomi phone, / Xiaomi 13 / MIUI 14.0.30 based on Android 13..not worked.  but when i used google contact app,it will do delete well.

Are you able to delete Xiaomi contacts on the Xiaomi phone using other Contacts app (not Google contacts)?

--------

Anyways, I just bought a [Xiaomi Redmi Note 12](https://www.mi.com/global/product/redmi-note-12/specs). It's a lot cheaper than the Xiaomi 13 but it also runs MIUI 14 based on Android 13. 

I figured that it's time to get a Xiaomi phone anyways for work, which I can get expensed (for free essentially). It's a very popular brand of phone next to the likes of Apple and Samsung. There have been many occasions where I needed a Xiaomi phone for work but did not have one lol.

My phone won't arrive until August 21. I will work on this "issue" (I'm not sure if it is a bug yet based on https://github.com/vestrel00/contacts-android/discussions/224#discussioncomment-2951518). Please wait around 3 weeks. I will debug this issue as soon as I can.

Thanks!

**Comment by asker517** [comment] 2023-08-08 08:02
@vestrel00  Wow...very appreciated!! 😄

**Comment by vestrel00** [comment] 2023-08-14 02:12
Hey @asker517 ! I got my Xiaomi phone much much earlier than expected  😁 I'm finally able to debug/verify this issue.

It seems like the discussions in https://github.com/vestrel00/contacts-android/discussions/224#discussioncomment-2951518 is correct. I verified this myself. I was not aware of this until I got my [Xiaomi Redmi Note 12](https://www.mi.com/global/product/redmi-note-12/specs) running MIUI Global 14.0.12 but it seems like the Google Contacts app is the default contacts app that comes pre-installed with (global) Xiaomi phones.

The default Contacts app, in my case the Google Contacts app, is able to delete Xiaomi contacts just fine. 

https://github.com/vestrel00/contacts-android/assets/4332753/77a06c3f-ba77-448f-b5ea-d3cee5c98de0

All other 3rd party contacts apps from the Google Play store was not able to delete Xiaomi contacts. Same thing with the sample app provided in this repository.

https://github.com/vestrel00/contacts-android/assets/4332753/b87a0000-57bc-4b22-8db5-a3af0ba7363a

https://github.com/vestrel00/contacts-android/assets/4332753/ce4eecfe-b170-4fb2-8405-350b3198a519

https://github.com/vestrel00/contacts-android/assets/4332753/f6d57568-c723-4488-bf43-3f2f1f14fa98

https://github.com/vestrel00/contacts-android/assets/4332753/1b977c6a-b15c-4d13-9296-14f19f46c4be

------

The issue seems to be that Xiaomi contacts are not deletable by 3rd party apps 😞 I'm not sure why. In any case, I'm closing this issue. Feel free to reopen it if you want to debug it yourself and maybe find a solution 🤞 ❤️

**Closed by vestrel00** 2023-08-14 02:12 UTC
Labels: question
